apiVersion: v2
name: onecx-user-profile-avatar-svc
version: 0.0.0
appVersion: 0.0.0
description: Onecx user-profile-avatar service
keywords:
  - tenant
sources:
  - https://github.com/onecx/onecx-user-profile-avatar-svc
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: ^0
    repository: oci://ghcr.io/onecx/charts